import Head from "next/head";
import Image from "next/image";
import { Button } from "~/components/ui/button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Harmony Share</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="from-bg-primary py-10 text-center">
        <div className="container mx-auto">
          <h1 className="mb-4 text-5xl font-bold">Welcome to Harmony Share</h1>
          <p className="text-xl">
            Collaboratively curate playlists of your favorite songs with friends
            and music enthusiasts.
          </p>
          <div className="mt-8">
            <Button className="px-6 py-6 " variant={"outline"}>
              Get Started
            </Button>
          </div>
        </div>
      </header>

      <main className="flex-1">
        <section className="container mx-auto px-4 py-10">
          <h2 className="mb-8 text-3xl font-semibold">Features</h2>
          <div className="grid grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-3">
            <div className="rounded-lg bg-secondary p-6 shadow-md">
              <h3 className="mb-4 text-2xl font-semibold">
                Create and Manage Playlists
              </h3>
              <p>
                Create your own playlists and customize them with descriptions
                and cover images.
              </p>
            </div>
            <div className="rounded-lg bg-secondary p-6 shadow-md">
              <h3 className="mb-4 text-2xl font-semibold">
                Collaborate with Friends
              </h3>
              <p>
                Invite your friends to join your playlists and curate the
                perfect collection together.
              </p>
            </div>

            <div className="rounded-lg bg-secondary p-6 shadow-md">
              <h3 className="mb-4 text-2xl font-semibold">
                Real-time Collaboration
              </h3>
              <p>
                Experience real-time updates when collaborating on playlists
                with friends.
              </p>
            </div>
          </div>
        </section>

        <section className="bg-bg-secondary py-16">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-center text-3xl font-semibold">
              What People Are Saying
            </h2>
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
              {/* Testimonial cards */}
            </div>
          </div>
        </section>

        <section className="bg-bg-primary py-16">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-center text-3xl font-semibold ">
              How It Works
            </h2>
            <div className="grid grid-cols-1 items-center gap-8 md:grid-cols-2">
              <div>
                <Image
                  src="https://via.placeholder.com/400"
                  width={400}
                  height={400}
                  alt="How It Works"
                  className="rounded-lg"
                />
              </div>
              <div className="text-lg">
                <p>
                  Harmony Share is a platform that allows you to create and
                  manage playlists of your favorite songs collaboratively with
                  friends and music enthusiasts.
                </p>
                <p>
                  To get started, sign up with your Spotify account and start
                  creating your own playlists. You can set the privacy of your
                  playlists as private, invite-only, public-read, or
                  public-edit, depending on who you want to share the playlist
                  with.
                </p>
                <p>
                  Once you have created a playlist, you can invite your friends
                  to collaborate on it. Friends with the &apos;edit&apos;
                  permission can add or remove songs, while others with
                  &apos;read&apos; permission can view and listen to the
                  playlist.
                </p>
                <p>
                  The real-time collaboration feature ensures that all changes
                  are updated instantly, making playlist curation a seamless and
                  enjoyable experience.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="bg-bg-secondary py-16">
          <div className="container mx-auto px-4">
            <h2 className="mb-8 text-center text-3xl font-semibold">
              Join the Community
            </h2>
            <div className="grid grid-cols-1 items-center gap-8 md:grid-cols-2">
              <div>
                <Image
                  src="https://via.placeholder.com/400"
                  width={400}
                  height={400}
                  alt="Join the Community"
                  className="rounded-lg"
                />
              </div>
              <div>
                <h3 className="mb-4 text-2xl font-semibold">
                  Connect with Like-Minded Music Lovers
                </h3>
                <p>
                  Harmony Share is more than just a playlist platform; it&apos;s
                  a thriving community of music enthusiasts. Join the community
                  to discover new music, discuss your favorite songs, and
                  exchange playlist ideas.
                </p>
                <h3 className="mb-4 mt-6 text-2xl font-semibold">
                  Get Inspired by Featured Playlists
                </h3>
                <p>
                  Our featured playlists section showcases handpicked
                  collections by our community members and music experts.
                  Explore a diverse range of playlists to find the perfect
                  soundtrack for any occasion.
                </p>
                <h3 className="mb-4 mt-6 text-2xl font-semibold">
                  Stay Updated with Latest Music Trends
                </h3>
                <p>
                  Stay in the loop with the latest music trends and releases.
                  Our community members are always sharing their favorite new
                  tracks and artists, ensuring you never miss a beat.
                </p>
                <div className="mt-8">
                  <Button className="px-6 py-6 " variant={"outline"}>
                    Join Now
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Add more sections, e.g., Featured Playlists, Latest Updates, etc. */}
      </main>
    </>
  );
}
